const CARD_COUNT = 18;
const CARD_COUNT_PER_STEP = 5;
const MAX_DESCRIPTION_LENGTH = 140;
const TEXT_LENGTH = 139;
const MAX_COUNT = 5;
const MAX_RAITING = 10;
const ACTORS_MAX_COUNT = 3;
const MIN_RANGE = 1;
const COMMENT_COUNT = 10;
const SORT_COUNT = 2;

export { CARD_COUNT, CARD_COUNT_PER_STEP, MAX_DESCRIPTION_LENGTH, TEXT_LENGTH, MAX_COUNT, MAX_RAITING, ACTORS_MAX_COUNT, MIN_RANGE, COMMENT_COUNT,SORT_COUNT };
